/*
 * Copyright 2026 NexFlow Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.nexflow.ui.ai

import com.nexflow.core.flowschema.ActionJson
import com.nexflow.core.flowschema.FlowJson
import com.nexflow.core.flowschema.TriggerJson
import java.util.UUID
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class FlowDiffTest {

    private fun config(vararg pairs: Pair<String, String>) =
        JsonObject(pairs.toMap().mapValues { JsonPrimitive(it.value) })

    private fun action(type: String, vararg config: Pair<String, String>) = ActionJson(
        // Ids are always freshly generated by the model, so they must not affect the diff
        id = UUID.randomUUID().toString(),
        type = type,
        config = config(*config),
        order = 0,
        enabled = true,
    )

    private fun flow(vararg actions: ActionJson, triggers: List<TriggerJson> = emptyList()) = FlowJson(
        schemaVersion = 1,
        id = "flow-1",
        name = "Drive mode",
        description = "",
        tags = emptyList(),
        enabled = false,
        createdAt = "2026-01-01T00:00:00Z",
        updatedAt = "2026-01-01T00:00:00Z",
        triggers = triggers,
        triggerLogic = "ANY",
        conditions = emptyList(),
        // Ordered by the position they were passed in
        actions = actions.mapIndexed { index, a -> a.copy(order = index) },
        variables = emptyList(),
    )

    @Test
    fun `an identical proposal has no changes`() {
        val current = flow(action("TOAST", "message" to "hi"), action("SET_VOLUME", "level" to "15"))
        val proposed = flow(action("TOAST", "message" to "hi"), action("SET_VOLUME", "level" to "15"))

        val diff = diffFlows(current, proposed)

        assertTrue(diff.isEmpty)
        assertTrue(diff.actions.all { it.kind == DiffKind.UNCHANGED })
    }

    @Test
    fun `an edited step is one CHANGED row, not a delete plus an add`() {
        val current = flow(action("TOAST", "message" to "hi"), action("SET_VOLUME", "level" to "8"))
        val proposed = flow(action("TOAST", "message" to "hi"), action("SET_VOLUME", "level" to "15"))

        val diff = diffFlows(current, proposed)

        assertFalse(diff.isEmpty)
        val changed = diff.actions.single { it.kind != DiffKind.UNCHANGED }
        assertEquals(DiffKind.CHANGED, changed.kind)
        assertEquals("SET_VOLUME", changed.type)
        // The whole point: which field, from what, to what
        assertEquals(listOf("level"), changed.changedKeys)
        assertEquals("8", changed.previousConfig["level"])
        assertEquals("15", changed.config["level"])
    }

    @Test
    fun `a step inserted in the middle marks only that step`() {
        val current = flow(action("TOAST", "message" to "a"), action("TOAST", "message" to "c"))
        val proposed = flow(
            action("TOAST", "message" to "a"),
            action("TOAST", "message" to "b"),
            action("TOAST", "message" to "c"),
        )

        val diff = diffFlows(current, proposed)

        assertEquals(
            listOf(DiffKind.UNCHANGED, DiffKind.ADDED, DiffKind.UNCHANGED),
            diff.actions.map { it.kind },
        )
        assertEquals("b", diff.actions[1].config["message"])
    }

    @Test
    fun `a deleted step is marked removed and nothing else moves`() {
        val current = flow(
            action("TOAST", "message" to "a"),
            action("SET_VOLUME", "level" to "9"),
            action("TOAST", "message" to "c"),
        )
        val proposed = flow(action("TOAST", "message" to "a"), action("TOAST", "message" to "c"))

        val diff = diffFlows(current, proposed)

        assertEquals(
            listOf(DiffKind.UNCHANGED, DiffKind.REMOVED, DiffKind.UNCHANGED),
            diff.actions.map { it.kind },
        )
        assertEquals("SET_VOLUME", diff.actions[1].type)
    }

    @Test
    fun `reordering shows as a move, not as everything having changed`() {
        val current = flow(action("TOAST", "message" to "a"), action("SET_VOLUME", "level" to "9"))
        val proposed = flow(action("SET_VOLUME", "level" to "9"), action("TOAST", "message" to "a"))

        val diff = diffFlows(current, proposed)

        // One step moved: it reads as that step removed from here and added over there,
        // while the step it jumped over stays untouched.
        assertEquals(1, diff.actions.count { it.kind == DiffKind.UNCHANGED })
        assertEquals(1, diff.actions.count { it.kind == DiffKind.ADDED })
        assertEquals(1, diff.actions.count { it.kind == DiffKind.REMOVED })
    }

    @Test
    fun `retiming a trigger is a change to that trigger`() {
        val current = flow(triggers = listOf(TriggerJson("t1", "TIME", config("time" to "07:00"))))
        val proposed = flow(triggers = listOf(TriggerJson("t2", "TIME", config("time" to "08:00"))))

        val changed = diffFlows(current, proposed).triggers.single()

        assertEquals(DiffKind.CHANGED, changed.kind)
        assertEquals(listOf("time"), changed.changedKeys)
        assertEquals("07:00", changed.previousConfig["time"])
    }

    @Test
    fun `swapping the trigger for a different kind is a replacement, not an edit`() {
        // MANUAL → TIME isn't "a field changed"; the flow is now started by something else
        // entirely, and the diff should say so rather than blur it into one row.
        val current = flow(triggers = listOf(TriggerJson("t1", "MANUAL", config())))
        val proposed = flow(
            triggers = listOf(TriggerJson("t2", "TIME", config("time" to "08:00"))),
        )

        assertEquals(
            listOf(DiffKind.REMOVED, DiffKind.ADDED),
            diffFlows(current, proposed).triggers.map { it.kind },
        )
    }

    @Test
    fun `differing ids alone never count as a change`() {
        // The model can't see ids, so it invents new ones on every proposal — if they leaked
        // into the comparison every single row would read as changed.
        val current = flow(action("TOAST", "message" to "hi"))
        val proposed = flow(action("TOAST", "message" to "hi"))

        assertTrue(diffFlows(current, proposed).isEmpty)
    }
}
